/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String filter = "assets/images/filter.svg";
  static const String logo = "assets/images/logo.png";
  static const String more = "assets/images/more.svg";
  static const String settings = "assets/images/settings.svg";
  static const String notification = "assets/images/notification.svg";
  static const String logoSVG = "assets/images/logo.svg";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String check = "assets/images/check.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
  static const String offline = "assets/images/offline.png";
  static const String user = "assets/images/user.png";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String errorSnackBar = "assets/images/error_snack_bar.svg";
  static const String warningSnackBar = "assets/images/warning_snack_bar.svg";
  static const String successSnackBar = "assets/images/success_snack_bar.svg";
  static const String backArrow = "assets/images/navigation-back-arrow-svgrepo-com.svg";
}
